In [1]:
import os
import numpy as  np
import pandas as pd

In [2]:
wd = '/Users/ewenwang/OneDrive/IBM/Project_ICBC/code_wu'
os.chdir(wd)
datafile = 'lc_2016Q3_clean.csv'
data = pd.read_csv(datafile, header=0)
data.info()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (13,35) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95210 entries, 0 to 95209
Data columns (total 91 columns):
Unnamed: 0                        95210 non-null int64
loan_amnt                         95210 non-null float64
term                              95210 non-null object
int_rate                          95210 non-null float64
installment                       95210 non-null float64
emp_title                         89516 non-null object
emp_length                        95210 non-null int64
home_ownership                    95210 non-null object
annual_inc                        95210 non-null float64
verification_status               95210 non-null object
issue_d                           95210 non-null object
loan_status                       95210 non-null float64
pymnt_plan                        95210 non-null object
desc                              6 non-null object
purpose                           95210 non-null object
title                             90065 non-null object
zip_code                          95210 non-null object
addr_state                        95210 non-null object
dti                               95210 non-null float64
delinq_2yrs                       95210 non-null float64
earliest_cr_line                  95210 non-null object
inq_last_6mths                    95210 non-null float64
mths_since_last_delinq            51229 non-null float64
mths_since_last_record            18903 non-null float64
open_acc                          95210 non-null float64
pub_rec                           95210 non-null float64
revol_bal                         95210 non-null float64
revol_util                        95151 non-null object
total_acc                         95210 non-null float64
initial_list_status               95210 non-null object
collections_12_mths_ex_med        95210 non-null float64
mths_since_last_major_derog       28125 non-null float64
application_type                  95210 non-null object
annual_inc_joint                  501 non-null float64
dti_joint                         501 non-null float64
verification_status_joint         501 non-null object
acc_now_delinq                    95210 non-null float64
tot_coll_amt                      95210 non-null float64
tot_cur_bal                       95210 non-null float64
open_acc_6m                       95210 non-null float64
open_il_6m                        95210 non-null float64
open_il_12m                       95210 non-null float64
open_il_24m                       95210 non-null float64
mths_since_rcnt_il                92660 non-null float64
total_bal_il                      95210 non-null float64
il_util                           82017 non-null float64
open_rv_12m                       95210 non-null float64
open_rv_24m                       95210 non-null float64
max_bal_bc                        95210 non-null float64
all_util                          95204 non-null float64
total_rev_hi_lim                  95210 non-null float64
inq_fi                            95210 non-null float64
total_cu_tl                       95210 non-null float64
inq_last_12m                      95210 non-null float64
acc_open_past_24mths              95210 non-null float64
avg_cur_bal                       95210 non-null float64
bc_open_to_buy                    94160 non-null float64
bc_util                           94126 non-null float64
chargeoff_within_12_mths          95210 non-null float64
delinq_amnt                       95210 non-null float64
mo_sin_old_il_acct                92660 non-null float64
mo_sin_old_rev_tl_op              95210 non-null float64
mo_sin_rcnt_rev_tl_op             95210 non-null float64
mo_sin_rcnt_tl                    95210 non-null float64
mort_acc                          95210 non-null float64
mths_since_recent_bc              94212 non-null float64
mths_since_recent_bc_dlq          24968 non-null float64
mths_since_recent_inq             85581 non-null float64
mths_since_recent_revol_delinq    35158 non-null float64
num_accts_ever_120_pd             95210 non-null float64
num_actv_bc_tl                    95210 non-null float64
num_actv_rev_tl                   95210 non-null float64
num_bc_sats                       95210 non-null float64
num_bc_tl                         95210 non-null float64
num_il_tl                         95210 non-null float64
num_op_rev_tl                     95210 non-null float64
num_rev_accts                     95210 non-null float64
num_rev_tl_bal_gt_0               95210 non-null float64
num_sats                          95210 non-null float64
num_tl_120dpd_2m                  91951 non-null float64
num_tl_30dpd                      95210 non-null float64
num_tl_90g_dpd_24m                95210 non-null float64
num_tl_op_past_12m                95210 non-null float64
pct_tl_nvr_dlq                    95210 non-null float64
percent_bc_gt_75                  94156 non-null float64
pub_rec_bankruptcies              95210 non-null float64
tax_liens                         95210 non-null float64
tot_hi_cred_lim                   95210 non-null float64
total_bal_ex_mort                 95210 non-null float64
total_bc_limit                    95210 non-null float64
total_il_high_credit_limit        95210 non-null float64
dtypes: float64(73), int64(2), object(16)
memory usage: 66.1+ MB

In [3]:
data.head()

,Unnamed: 0,loan_amnt,term,int_rate,installment,emp_title,emp_length,home_ownership,annual_inc,verification_status,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,0,15000.0,36 months,13.99,512.60,Fiscal Director,2,RENT,55000.0,Not Verified,...,0.0,5.0,100.0,33.3,0.0,0.0,147587.0,140492.0,30200.0,108587.0
1,1,2600.0,36 months,8.99,82.67,Loaner Coordinator,3,RENT,35000.0,Source Verified,...,0.0,0.0,100.0,0.0,0.0,0.0,73227.0,19497.0,50200.0,20527.0
2,2,32200.0,60 months,21.49,880.02,warehouse/supervisor,10,MORTGAGE,65000.0,Not Verified,...,0.0,2.0,100.0,40.0,1.0,0.0,199969.0,24934.0,13900.0,15886.0
3,3,10000.0,36 months,11.49,329.72,Teacher,10,OWN,55900.0,Not Verified,...,0.0,6.0,100.0,66.7,0.0,0.0,68831.0,38085.0,13500.0,36431.0
4,4,6000.0,36 months,13.49,203.59,SERVICE MGR,5,RENT,33000.0,Not Verified,...,0.0,1.0,100.0,100.0,0.0,0.0,17500.0,15393.0,4800.0,12700.0

In [ ]:
data = data.

In [4]:
print(data.loan_status.sum())
print(data.shape)

92511
(95210, 87)

In [5]:
default_rate = 1-data.loan_status.sum()/data.shape[0]
print(default_rate)

0.0283478626195

In [12]:
from datetime import datetime
#import xgboost as xgb
#from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn import cross_validation, metrics   
from sklearn.metrics import accuracy_score
from sklearn.metrics import auc 
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
from matplotlib.pylab import rcParams
#import seaborn as sns
#%matplotlib inline

In [14]:
target = 'loan_status'
predictors = [x for x in data.columns if x not in [target]]
test_size, seed = 0.3, 7
dtrain, dtest = train_test_split(data, test_size=test_size, random_state=seed)